-- =============================================================================
-- Shubharambh Infra Advisors — SQLite Schema
-- Generated by: sqlite3 db.sqlite < sql/schema.sqlite.sql
-- =============================================================================

PRAGMA foreign_keys = ON;

DROP TABLE IF EXISTS inquiries;
DROP TABLE IF EXISTS testimonials;
DROP TABLE IF EXISTS partners;
DROP TABLE IF EXISTS team_members;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS site_settings;

-- -----------------------------------------------------------------------------
-- Site-wide settings (single row, id = 1)
-- -----------------------------------------------------------------------------
CREATE TABLE site_settings (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  company_name    TEXT NOT NULL,
  tagline         TEXT NOT NULL,
  phone_primary   TEXT NOT NULL,
  phone_whatsapp  TEXT NOT NULL,
  email_primary   TEXT NOT NULL,
  email_secondary TEXT,
  address_line    TEXT NOT NULL,
  map_embed_url   TEXT,
  rera_number     TEXT,
  rera_notice     TEXT,
  facebook_url    TEXT,
  instagram_url   TEXT,
  linkedin_url    TEXT,
  youtube_url     TEXT,
  twitter_url     TEXT,
  hero_title      TEXT NOT NULL DEFAULT 'Find Your Luxury Home',
  hero_subtitle   TEXT NOT NULL DEFAULT 'BEST REAL ESTATE PROPERTY CONSULTANT IN DELHI/NCR',
  about_heading   TEXT NOT NULL DEFAULT 'Get To Know About Shubharambh Infra',
  about_body      TEXT,
  updated_at      TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- -----------------------------------------------------------------------------
-- Projects (rich schema with configurations, amenities, connectivity, USPs)
-- -----------------------------------------------------------------------------
CREATE TABLE projects (
  id             INTEGER PRIMARY KEY AUTOINCREMENT,
  slug           TEXT NOT NULL UNIQUE,
  name           TEXT NOT NULL,
  tagline        TEXT,
  builder        TEXT NOT NULL,
  location       TEXT NOT NULL,
  city           TEXT NOT NULL DEFAULT 'Noida',
  price_display  TEXT NOT NULL,
  property_type  TEXT NOT NULL,
  configurations TEXT,         -- e.g. "3 / 4 / 5 BHK Apartments"
  sizes          TEXT,         -- e.g. "3217 – 6220 sq ft (super area)"
  possession     TEXT,         -- e.g. "April 2028"
  rera_id        TEXT,
  description    TEXT,         -- long intro paragraphs
  amenities      TEXT,         -- JSON array of strings
  connectivity   TEXT,         -- JSON array of strings
  usps           TEXT,         -- JSON array of strings
  cover_image    TEXT,         -- relative path under /uploads/
  is_featured    INTEGER NOT NULL DEFAULT 0,
  is_active      INTEGER NOT NULL DEFAULT 1,
  sort_order     INTEGER NOT NULL DEFAULT 0,
  created_at     TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at     TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_projects_featured_active ON projects (is_featured, is_active, sort_order);
CREATE INDEX idx_projects_active          ON projects (is_active);

-- -----------------------------------------------------------------------------
-- Testimonials
-- -----------------------------------------------------------------------------
CREATE TABLE testimonials (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  client_name TEXT NOT NULL,
  city        TEXT,
  rating      INTEGER NOT NULL DEFAULT 5,
  quote       TEXT NOT NULL,
  is_active   INTEGER NOT NULL DEFAULT 1,
  sort_order  INTEGER NOT NULL DEFAULT 0,
  created_at  TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_testimonials_active ON testimonials (is_active, sort_order);

-- -----------------------------------------------------------------------------
-- Partners
-- -----------------------------------------------------------------------------
CREATE TABLE partners (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  name       TEXT NOT NULL,
  logo       TEXT,
  website    TEXT,
  is_active  INTEGER NOT NULL DEFAULT 1,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_partners_active ON partners (is_active, sort_order);

-- -----------------------------------------------------------------------------
-- Team
-- -----------------------------------------------------------------------------
CREATE TABLE team_members (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  full_name  TEXT NOT NULL,
  title      TEXT NOT NULL,
  bio        TEXT,
  photo      TEXT,
  linkedin   TEXT,
  twitter    TEXT,
  email      TEXT,
  is_active  INTEGER NOT NULL DEFAULT 1,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_team_active ON team_members (is_active, sort_order);

-- -----------------------------------------------------------------------------
-- Inquiries
-- -----------------------------------------------------------------------------
CREATE TABLE inquiries (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  source       TEXT NOT NULL DEFAULT 'contact' CHECK (source IN ('contact','popup','project')),
  full_name    TEXT NOT NULL,
  email        TEXT,
  phone        TEXT NOT NULL,
  city         TEXT,
  message      TEXT,
  project_id   INTEGER,
  project_name TEXT,
  ip_address   TEXT NOT NULL,
  user_agent   TEXT,
  status       TEXT NOT NULL DEFAULT 'new' CHECK (status IN ('new','read','archived')),
  created_at   TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE SET NULL
);
CREATE INDEX idx_inquiries_status_created ON inquiries (status, created_at);
CREATE INDEX idx_inquiries_ip_created     ON inquiries (ip_address, created_at);
